language: ruby

rvm:
  - 2.6
script: bundle exec jekyll build
install:
  - bundle install
  - pip install --user awscli
deploy:
  # - provider: s3
    # on:
      # branch: master
    # access_key_id: $AWS_ACCESS_KEY_ID
    # secret_access_key: $AWS_SECRET_ACCESS_KEY
    # bucket: jgdr20
    # skip_cleanup: true
    # local_dir: _site
    # region: eu-west-1
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: 
      - aws s3 sync _site s3://jgdr20 --region=eu-west-1 --exclude "assets*" --exclude "jmm\archive*" --delete
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: 
      - aws s3 sync _site/assets s3://jgdr20/assets --region=eu-west-1 --size-only --delete
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: 
      - aws cloudfront create-invalidation --distribution-id E32SB4NXD0EYKP --paths '/*'
notifications:
  email:
    recipients:
      - admin@jgdr20.com
    on_success: always # default: change
    on_failure: always # default: always