language: ruby

rvm:
  - 2.6
script: bundle exec jekyll build
install: bundle install
deploy:
  - provider: s3
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: jgdr20
    skip_cleanup: true
    local_dir: _site
    region: eu-west-1
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: 
      - aws cloudfront create-invalidation --distribution-id E32SB4NXD0EYKP --paths '/*'