---
title: JR Blog
baseurl: "/jgdr20/Blog"
desc: A Quick and Dirty Blog
about: A London-based support monkey with several years experience in MS SQL, application and OS support, plus several more years of customer service.
image:
excerpt_separator: "<!-- more -->"
markdown: jekyll-commonmark
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
